import React from 'react';
import { 
    LayoutTemplate, 
    Image as ImageIcon, 
    MessageSquare, 
    Send, 
    Loader2, 
    PenTool, 
    Check, 
    Upload,
    ZoomIn,
    Layers,
    Scissors,
    Download,
    Sun,
    Moon,
    GripVertical,
    ArrowLeft,
    X,
    Clapperboard,
    Film,
    Camera,
    Trash2,
    ChevronRight,
    ChevronLeft,
    PanelRightClose,
    PanelRightOpen,
    Eraser,
    Brush,
    Maximize2,
    Hand,
    Calculator,
    ChartPie
} from 'lucide-react';

export const Icons = {
    Studio: LayoutTemplate,
    Blueprint: Layers,
    Layers: Layers,
    Image: ImageIcon,
    Chat: MessageSquare,
    Send: Send,
    Spinner: Loader2,
    Edit: PenTool,
    PenTool: PenTool,
    Check: Check,
    Upload: Upload,
    Zoom: ZoomIn,
    Cut: Scissors,
    Scissors: Scissors,
    Save: Download,
    Download: Download,
    Sun: Sun,
    Moon: Moon,
    Drag: GripVertical,
    ArrowLeft: ArrowLeft,
    X: X,
    Runway: Clapperboard,
    Video: Film,
    Camera: Camera,
    Trash: Trash2,
    ChevronRight: ChevronRight,
    ChevronLeft: ChevronLeft,
    PanelClose: PanelRightClose,
    PanelOpen: PanelRightOpen,
    Eraser: Eraser,
    Brush: Brush,
    Maximize: Maximize2,
    Hand: Hand,
    Calculator: Calculator,
    Chart: ChartPie
};